name: Update flake.lock

on:
  schedule:
    # run every saturday
    - cron: '0 0 * * 6'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v27

      - name: Update and create PR
        uses: DeterminateSystems/update-flake-lock@v21
        with:
          commit-msg: 'nix: update flake.lock'
          pr-title: 'nix: update flake.lock'
          token: ${{ github.token }}
